name: san_zi_jing
description: 亲子共读三字经 - AI配音朗读 + 家长孩子跟读录音对比
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  just_audio: 0.9.38
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
